### ISSUE TITLE
regex support for links

### ISSUE THREAD

**Issue by boessi** [girlfriend-technology/xtoy-extension#1]
Noticed that Regex are only supported for Text replacement. Would it be possible to add it for Links as well?

Much appreciate and keep up the good work

**Comment by ZicklePop** [comment]
Absolutely! I just got a review on the App Store asking for regex with group support, and this is totally something I want to implement in the near future.

**Comment by ZicklePop** [comment]
Added in the latest commit 530d5661d3e673ccab21f226ef4abeffd5ac99ba. Will work on bundling and releasing soon.

**Comment by ZicklePop** [comment]
This feature is available in the latest version for Safari, Chrome, and Firefox. Edge reviews take a while. I hope you enjoy :)
