### ISSUE TITLE
Links Not Changing on Some Sites

### ISSUE THREAD

**Issue by kwmc-lucas** [girlfriend-technology/xtoy-extension#13]
Love the app.

I've noticed that some websites don't seem to respect my rules for links.

For example, this is my rule for YouTube:
`/((?:https?:\/\/)?(?:www\.|m\.)?(?:youtu\.be|youtube.com))((\/embed)?)/I` becomes `https://piped.kavin.rocks`

This works pretty much everywhere, however I've noticed that Feedbin and DuckDuckGo still go to YouTube.

With the above rule (and Link Mode enabled) if you visit these results and click on the YouTube link, it will take you to Piped:
https://search.brave.com/search?q=fly+don%27t+hug

However, click on the same video link on DuckDuckGo and you'll be taken to YouTube:
https://duckduckgo.com/?q=fly%20don't%20hug

Similarly, when viewing YouTube feeds in Feedbin, the links go straight to YouTube.

Any idea why I'm seeing a different result on some sites and not others?

P.S. I've just been playing with https://github.com/johnste/finicky which allows rewriting links from elsewhere, so even if I'm clicking on something in iMessage I've got everything matched to my XtoY rules - it's great!

**Comment by ZicklePop** [comment]
Oh nice! I use Feedbin and DuckDuckGo too. I'll have to play with Finicky :)

The issue you are experiencing comes from how I need to be watching the webpage for changes, which is what issue #10 is going to fix. It's been a wild year and I hope to get to this fix real soon.

Thank you!

**Comment by kwmc-lucas** [comment]
@ZicklePop ah, thanks for the quick response and answer!

Yes, that must be it as I've also noticed it with things like Twitter embeds, so all those things must be loading in after.

That's great to hear that you've already spotted it. Let me know if you need help with testing if/when you do get time.

**Comment by ZicklePop** [comment]
Quick update: I have a partial fix right now, but I will need to dig deeper.

**Comment by kwmc-lucas** [comment]
Amazing, thanks Melanie, I look forward to trying out the Safari version once it's been approved :)

**Comment by kwmc-lucas** [comment]
It's come through on the iOS App Store, but not macOS, is there sometimes a delay between platforms?

**Comment by ZicklePop** [comment]
There is. Mac should be out now though.

**Comment by kwmc-lucas** [comment]
Yay, I've got it now - looks to be working well!

YouTube feeds in Feedbin and articles with Twitter embeds ([like this one](https://newsletters.theatlantic.com/galaxy-brain/62ba500cbcbd490021aaef70/web3-crypto-movement-uses-marc-andreessen/)) now use the altered link.

However, Twitter feeds in Feedbin don't seem to use the altered links - are you seeing the same behaviour?

**Comment by ZicklePop** [comment]
![image](https://user-images.githubusercontent.com/318003/178516993-6bfc03ae-b9fe-4ee3-b922-c353ebde1fd5.png)

Using `/https?://(www.)*twitter.com/im` appears to work for me on Feedbin. It should always be the same. I know some links on Twitter's website do not work because the links are relative urls though, but I've not seen anything with Feedbin.

**Comment by ZicklePop** [comment]
![Screen Shot 2022-07-12 at 7 47 07 AM](https://user-images.githubusercontent.com/318003/178518931-e985c2df-0337-4acc-8084-cdbd1b56fc58.png)
Ok, I think I see where an issue may occur. URLs in tweets are all converted to Twitter's `t.co` short url service. Feedbin looks to put the full link in the link's title attribute, but on Twitter's website the full link is obscured too.

**Comment by kwmc-lucas** [comment]
@ZicklePop I was thinking the same! I've seen that on some sites with the shortened ones and I guess I'll have to write a new rule to change those?

What's confused me is within Feedbin, [copying the links](https://streamable.com/jxbz9u) or [inspecting the page](https://ibb.co/rMrVZFq) seems to show them as twitter.com URLs.

**Comment by ZicklePop** [comment]
What is your rule you're currently working with?

**Comment by ZicklePop** [comment]
try wrapping it `/regex goes here/gi` so when i do `/((?:https?://)?(?:pic.twitter.com|twitter.com|t.co))((/embed)?)/gi` I'm able to get it to replace the URLs.

**Comment by kwmc-lucas** [comment]
Yes, that's got it! Many thanks. It seems to be working perfectly everywhere now :)
