### ISSUE TITLE
Passthrough Variables

### ISSUE THREAD

**Issue by kwmc-lucas** [girlfriend-technology/xtoy-extension#14]
I've not been able to figure this one out, but perhaps I'm doing something silly.

I have a file storage server which provides different links, for example to download a file:
`https://filestorage.com/myfiles/1234569/download`

I would like to leave that one and others intact. However, one of the links is a stream which works in my media player:
`https://filestorage.com/myfiles/1234569/stream`

I'd like those to automatically open in my media player:
`iina://weblink?url=https://filestorage.com/myfiles/1234569/stream`

I could hypothetically find all `https://filestorage.com/myfiles/` occurrences and replace them with `iina://weblink?url=https://filestorage.com/myfiles/`, but that would break the other links used for downloading etc.

To counter that, I could Regex for just streams, but then the salient variable (1234569) would disappear in the process too.

Would it be possible to pick variables found in the Match (e.g. 1234569) and make them usable in the Replacement?

**Comment by ZicklePop** [comment]
Try setting X to `/^(?=https?://filestorage.com/myfiles/)/` or `/^(?=https?://filestorage.com/myfiles/\d*/(stream|watch))/` if you need more specificity and Y to `iina://weblink?url=`

This works by using [regex look-aheads](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions#other_assertions).

I hope this helps!

**Comment by kwmc-lucas** [comment]
Thanks @ZicklePop, that's **super** handy!

I had a play and this seems to work exactly as needed:
`(?:https?:\/\/)?filestorage.com\/myfiles\/(?=\d*\/stream)`

However, I think the file storage site has the same issue as #10, because the URLs aren't being re-written.

**Comment by kwmc-lucas** [comment]
I can confirm that this is now working with #10 !

However, because the URL appears again in the replacement and **X to Y** is now continuously checking for changes, I had to update the rule slightly:

Find X
`/^(?:https?:\/\/)?filestorage.com\/myfiles\/(?=\d*\/stream)/g`

Replace with Y
`iina://weblink?url=https://ilestorage.com/myfiles/`
